### ISSUE TITLE
Сгенерировать список id и дат диктантов

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#17]
Для этого сначала получить список дат диктантов у Маши

**Comment by Alenush** [comment]
Я не поняла это задание. Наверное проворонила. В смысле сгенерировать? 
У меня в базе они просто лежат и всё. Вынимаются, когда считается "следующий диктант".

**Comment by dendik** [comment]
Нам в вёрстку нужно приделывать айдишники диктантов как айдишники некоторых
элементов, чтобы через CSS+JS менять стиль оформления для пройденных и
активного диктанта. Поэтому Ксюше нужно знать список пар: айдишник-дата.

Понятно, чтобы он был у тебя, тебе нужно загрузить диктанты в базу, а для
этого нужно узнать их даты у Маши.
