### ISSUE TITLE
Сделать страницу, которая показывается, когда активного диктанта нет

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#20]
Учитывать, что бывает ситуация next_id == null. Сообщение, которое показывать в этом случае, получить от Маши.

**Comment by GrimGrinPilgrim** [comment]
если делать виджет с отсчетом, то его каждый раз заново генерировать придется. Или мы делаем его только до 2 ноября?

**Comment by dendik** [comment]
Предлагаю добавить в данные диктанта (в базу данных) адрес виджета с
обратным отсчётом. Тогда мы просто заведём 16 этих виджетов.

Алёна, что скажешь?

2015-10-27 23:25 GMT+03:00 kseniy notifications@github.com:

**Comment by GrimGrinPilgrim** [comment]
и мне кажется лучше это на отдельную стр вывести

**Comment by dendik** [comment]
> и мне кажется лучше это на отдельную стр вывести

Имеешь в виду сделать отдельным шаблоном? Алёна, что скажешь?
- 1 поле в базе. А выдавать мне его в шаблон? как сслыку на видео диктанта?
  > тогда вообще без проблем.
  > ТОлько ссылки киньте.

Ссылки сделаю.

PS. Алёна, отвечай, пожалуйста, reply to all, либо через сайт гитхаба
https://github.com/Alenush/zhivoeslovo/issues/20#issuecomment-151633358.

**Comment by Alenush** [comment]
ок. я тут. 
так. я не поняла про отдельный шаблон.
Какой у нас план? То есть когда диктанта нет у нас один шаблон выходит, когда есть тот появляется? и это по времени типа узнается?

**Comment by dendik** [comment]
Ксюша, Алёна, вы утрясли этот вопрос? Если да, то просьба отмечать это в тикете. Если нет, то Ксюша, ответь, пожалуйста, Алёне?

Всё равно, каким образом делается страница, генерируется она через js или через шаблоны на сервере. Лишь бы договориться. Кто первый может успеть добраться и сделать её, пусть и сделает так, как ему проще. И отпишите сюда в тот момент, когда начинаете делать. (А не когда заканчиваете).

**Comment by GrimGrinPilgrim** [comment]
## Н е совсем поняла вопроса, мы же вроде решили, что на стр просто будет меняться отсчитывалка вренени? 

Отправлено из Mail.Ru для Android четверг, 29 октября 2015г., 03:51 +0300 от dendik < notifications@github.com> :

**Comment by dendik** [comment]
Вроде сейчас работает.
