### ISSUE TITLE
Сделать отдельную вёрстку для оценки "см"

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#25]
NB. Алёна сейчас в этом случае в качестве оценки выдаёт не число, а именно строку "см".

На странице "см" мы не показывае разбора ошибок вообще.

**Comment by Alenush** [comment]
А мы разве не договорились, что я выкидываю 2, и Антон дальше с этим сам разбирается?
И мне так даже лучше, потому как в базе стоит поле Integer, и на строку "См." он ругается.

**Comment by dendik** [comment]
Окей, договорились, пусть будет 2.
