### ISSUE TITLE
Убрать все упоминания правильных ответов в предстоящих диктантах.

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#30]

**Comment by dendik** [comment]
Антон, Ксюша, файлик templates/write_dict.html смотрит на вас выжидательно. Боюсь менять в нём что-либо без вникания в код.

**Comment by Mannarox** [comment]
что то я не очень понял, что значит "Убрать все упоминания правильных ответов в предстоящих диктантах" ?

**Comment by dendik** [comment]
У нас сейчас в исходниках прямым текстом светится правильный ответ на
первый диктант.

**Comment by dendik** [comment]
Это нужно сделать срочно!!!

**Comment by Mannarox** [comment]
так мы посмотрели, вроде больше ничего не осталось, у нас в readme Только про мальчика лежит, который давно умер, и это не актуальный текст

**Comment by dendik** [comment]
https://github.com/Alenush/zhivoeslovo/blob/master/templates/write_dict.html#L105

**Comment by GrimGrinPilgrim** [comment]
## Я это собственноручно сегодня убрала. Этого быть не должно уже 

Отправлено из Mail.Ru для Android пятница, 30 октября 2015г., 13:56 +0300 от dendik < notifications@github.com> :

**Comment by dendik** [comment]
Но я снова тыкаю в это место в репозитории, и оно там есть... О_О

**Comment by Alenush** [comment]
СМОТРЕТЬ ВСЕМ. Ну нет же больше ответов на первый диктант?!

**Comment by dendik** [comment]
Всё ок
