### ISSUE TITLE
точка в конце предложения не считается за ошибку.

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#32]
Это к Ане

**Comment by Alenush** [comment]
Стоп. Если человек точку не поставил в конце. Так это ошибка или нет?
Я только добавила, чтобы считалась за ошибку.

**Comment by dendik** [comment]
Да, это ошибка.

Ошибка в том, что пока что она не считалась за ошибку :) Если протестировала, то закрой?

**Comment by dendik** [comment]
Всё ок?
