### ISSUE TITLE
Съезжают описания ошибок?

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#36]
Написала раздельно "не обыкновенными". Описание ошибки явно не то: "Написание букв на месте безударных гласных корня, которое не может быть установлено по общему правилу (непроверяемых гласных), определяется в словарном порядке (ПАС 34)"

**Comment by Alenush** [comment]
тут просто на букве О две ошибки висят. и вторая, про то, что раздельно, не вытаскивается пока =(
