### ISSUE TITLE
предложение со строчной буквы не считает за ошибку

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#37]
Это к Ане

**Comment by Alenush** [comment]
Просто в базе добавила на символ ошибку (что регистр не тот, надо с заглавной писать). норм?

**Comment by dendik** [comment]
Да, именно, только проследи, что этого одновременно с тобой не сделала Аня?
Она мне по телефону говорила, что она всё исправит просто ручками.

**Comment by Alenush** [comment]
Ну это я исправила в базе прям. А дальше надо просто в разметке всегда это делать.
