### ISSUE TITLE
Вывесить первые три видео

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#38]
Ссылка в письме 28 окт

**Comment by dendik** [comment]
Ссылки сделал.

**Comment by dendik** [comment]
Алёна, поправь, пожалуйста, в базе ссылку на первое видео. Она должна быть у тебя в почте.

**Comment by Alenush** [comment]
Так вроде в базе все три ссылки, которые ты присылал, разве нет?

**Comment by dendik** [comment]
На первый диктант висят котики

**Comment by Alenush** [comment]
https://www.youtube.com/embed/yioyW7KjuH0
Вот эта к первому диктанту. В той базе которую я послала в ответ на Анину разметку.
В той базе все три ссылки твои.

**Comment by dendik** [comment]
Да, мой глюк.
