### ISSUE TITLE
Добавить правила на лишние знаки препинания

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#39]
Аня обещала сделать.

**Comment by Alenush** [comment]
Это что? 
если человек типа написал лишнюю запятую - это считается за ошибку??? 
сейчас же он просто игнорит это. Ну то есть, если в базе такие места есть с комментариями адекватными, то не игнорит, а абы какие лишние просто пропускает. Чем так плохо?

**Comment by dendik** [comment]
Я ж написал в комментариях, что это задача Ане. (Она ещё не
зарегистрировалась? Попробуй ещё раз её пригласить в реп). Ей нужно в
скрипте добавить идентичное правило на конце каждого слова, где такого
правила не прописано уже ручками. И это там делается легко.

**Comment by avybornova** [comment]
Сделано.

**Comment by dendik** [comment]
Алёна, Аня. Залил свежую версиб БД (десять минут назад), лишние знаки препинания не дают ошибку. Где бага?

**Comment by avybornova** [comment]
У меня в таблице они все  размечены. Для первого диктанта. Ты какой тестишь?

**Comment by dendik** [comment]
Первый. В таком случае, вопрос к Алёне, загружена ли свежая версия первого диктанта в БД?

**Comment by dendik** [comment]
Вроде в общем всё ок, частные вопросы будут в других тикетах.
