### ISSUE TITLE
Ко всем датам подпись: время московское

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#41]

**Comment by dendik** [comment]
На всякий случай напоминаю: это ещё нужно сделать. (Хотя это, вроде, тривиально ж?) Часики привесить -- хорошо, но нужно словами сказать, что время по ним.

**Comment by GrimGrinPilgrim** [comment]
сделала, думаю как теперь передавать файлы  )))))

**Comment by dendik** [comment]
Кажется, нужно устраивать мастер-класс по репозиториям...

**Comment by GrimGrinPilgrim** [comment]
да стоит, мне вообще казалось, что когда мы работаем в колоборации на с9, то он думает, что мы, как бы, с одного компа изменения вносим...

**Comment by dendik** [comment]
Ну, логично. Потому, что это и вправду один компьютер: c9. Наверное, в этом
случае проще всего иметь каждому по локальной копии репозитория и на c9
пушить. Такого рода взаимодействие в гите очень хорошо проработано.
