### ISSUE TITLE
Потеря пробела не регистрируется

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#44]
написала слитно предлог со следующим словом - не считает за ошибку, а мы договаривались, что любое отсутствие пробела между словами - ошибка

**Comment by Alenush** [comment]
В первом диктанте есть "по незнакомому", это точно есть в базе и размечается. А если просто пробел человек забыл, то это не ошибка. Я не знаю, как это исправить уже.

**Comment by dendik** [comment]
Нынешняя договорённость, что мы реагируем только на размеченные ошибки,
действительно. Вопрос в том, правильно ли мы реагируем на разметку о том,
что два слова слиплись.
