### ISSUE TITLE
wishlist: на ожидании реакции сервера "подождите, идёт проверка" вместо "живое слово"

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#45]

**Comment by GrimGrinPilgrim** [comment]
поменяла - смотрится отвратно(((

**Comment by dendik** [comment]
Ну, если заказчик хочет, чтобы выглядело отвратительно, приходится ему
потакать... А если просто "идёт проверка" не будет лучше? Я думаю, Маша на
такой вариант согласится.

(Впрочем, вот это совсем мелочи, и нечего на них тратить силы)
