### ISSUE TITLE
Убрать время в диктантах на первую неделю.

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#46]

**Comment by GrimGrinPilgrim** [comment]
как я поняла время надо оставить на 1 неделе (зачем же тогда Маша говорила про московское время)

**Comment by dendik** [comment]
Московское время -- другой тикет. И это нужно везде, где упоминается
какое-либо время вообще.

Да, я опечатался в задаче. Нужно оставить только про первую неделю, про
остальные убрать.

**Comment by GrimGrinPilgrim** [comment]
А может приделать видеть с часами на сайт?  Чтоб было понятно который час в Москве

**Comment by GrimGrinPilgrim** [comment]
*виджет
