### ISSUE TITLE
Первые три диктанта: обратный отсчёт

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#5]

**Comment by dendik** [comment]
Всё-таки эта штука нужна, но не обязательно её делать своими руками, можно повесить ссылку на любой сервис с напоминалками.

Браться за это всё равно только после того, как сделано и протестировано всё основное.

**Comment by dendik** [comment]
Ксюш, ты сделала все ссылки, или только для первого?

**Comment by dendik** [comment]
Алёна, нужно добавить в модель ссылку на отсчёт. И воткнуть эту ссылку в шаблон.

**Comment by Alenush** [comment]
ок. только дайте мне ссылки на отчеты к первым трем диктантам. И кстати ссылки на видео тоже было бы круто сразу получить и туда добавить.

**Comment by dendik** [comment]
Ксюша, сделай, пожалуйста, три ссылки. Я поглядел на megatimer.ru и понял, что я не воспроизведу тот стиль, который подобрала ты.

**Comment by GrimGrinPilgrim** [comment]
уже у Алены

**Comment by dendik** [comment]
Тогда

**Comment by dendik** [comment]
Где ссылки на обратный отсчёт в вёрстке?

**Comment by dendik** [comment]
Это срочно! Нужно тестировать СЕЙЧАС.

**Comment by dendik** [comment]
Ксюш, поменяй, пожалуйста, таймеры на:

1-я программа - 21:11:00
2-я программа - 21:13:00
3-я программа - 21:10:00 ?

**Comment by Alenush** [comment]
в anons.html
src="{{ link }}"

**Comment by dendik** [comment]
Здесь сейчас правильные ссылки? На 21:10+ с копекйами? Если да, то закройте тикет. По внешности счётчиков я это не умею определять.
