### ISSUE TITLE
Уехала вёрстка валидатора почты

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#53]
Нужно, чтобы если валидатор не проходит, плашки не показывались. Иначе совсем непонятно, почему оно не работает.

**Comment by GrimGrinPilgrim** [comment]
## Не поняла про какую плашку ты говоришь. Поясни , пожалуйста 

Отправлено из Mail.Ru для Android воскресенье, 01 ноября 2015г., 18:27 +0300 от dendik < notifications@github.com> :

**Comment by dendik** [comment]
Про окошко ожидания ответа от сервера. Уж не знаю, почему Маша начала называть его плашками, но придерживаюсь её терминологии. То, где прыгают синие буквы.

**Comment by GrimGrinPilgrim** [comment]
поняла о чем ты. видимо вы еще не успели проверить получение данных, иначе заметили бы, что это заглушка, а самого сабмита не происходит))) я убрала заглушку и раскоментила код антона. Надо бы проверить и если что-то не так сказать Антону.

**Comment by dendik** [comment]
Антон, хватит притворяться, что ты нас не слышишь! Ты на этот тикет исполнителем назначен.

Сейчас стало лучше: он не пускает меня нажать на кнопку, если адрес неправильный. Но теперь, если он правильный, не происходит визуально ничего (хотя запрос и на send_results, и на success приходит)

**Comment by Mannarox** [comment]
просто не могу вызвать у себя ту же проблему что бы, посмотреть, что там именно

**Comment by dendik** [comment]
Мне в консоль приехало:

```
Ошибка выполнения ajax
antonJS.js (line 203)
```

И два запроса по сети:

GET
/zhivoeslovo/ajax/send_results/?dict_id=1&username=%D0%A5%D1%83%D0%BD&age=4&sex=male&city=%D0%92%D1%8D%D0%B9&edu=%D0%91%D0%B8%D0%BD&prof=%D0%92%D0%B0%D1%83&email=me.dendik%
40gmail.com&confirmation=3a931002-8dbe-4823-87d3-156dde658186

-> 302

И

GET /zhivoeslovo/success/

-> 200, и там текст про успех.

**Comment by GrimGrinPilgrim** [comment]
## Антон аякс убрал, я заглушку убрала - вроде безошибочная комбинация, которая работает:-)

Отправлено из Mail.Ru для Android понедельник, 02 ноября 2015г., 02:31 +0300 от dendik < notifications@github.com> :

**Comment by dendik** [comment]
Можешь пояснить?

**Comment by GrimGrinPilgrim** [comment]
залила новую версию - рабочую.

**Comment by GrimGrinPilgrim** [comment]
короче, создала себе отдельное облако, с него могу пушить)))

**Comment by dendik** [comment]
Ура, работает!
