### ISSUE TITLE
Карусель очень медленная

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#59]
У меня прокурчивает на несколько букв в сторону, и останавливается. Чтобы увидеть очередной словарь нужно нажать раз 10-15

**Comment by GrimGrinPilgrim** [comment]
странно, какой браузер ?

**Comment by dendik** [comment]
Мозилла. Ты что-нибудь в этих окрестностях недавно правила? У меня такое поведение с утра (раньше не смотрел).

**Comment by Alenush** [comment]
О, и у меня мозила. и тоже довольно медленно. Но вот с последним пушем вроде побыстрее стало. Может в других браузерах лучше.

**Comment by GrimGrinPilgrim** [comment]
правила, но я на хроме, на кроссбраузерность не тестила, т.к. брала свои старые наработки, в которых была уверенна. Щас посмотрю еще раз.

**Comment by GrimGrinPilgrim** [comment]
диагноз понятен, все норм - это не кроссбраузерность (слава тебе Господи). Где то параметры сбиваются, получается, что если карусель сразу видна - все норм, а если сначала скрыта, а потом показывается в функцию другие значения приходят((( если это не критично я утром посмотрю, в крайнем случае ее легко заменить на обычный вариант

**Comment by dendik** [comment]
До середины дня живёт без проблем. (И в принципе эта штука раздражающая, но
не критичная. Почти никто не будет эти словари листать, а когда и будет,
время уже не тикает, так что всё ок).

**Comment by dendik** [comment]
Ты починила, или она у меня случайно работает?

**Comment by GrimGrinPilgrim** [comment]
починила, больше не сломается)

**Comment by dendik** [comment]
Отлично!
