### ISSUE TITLE
Добавить текст про правила написания диктанта

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#62]
> Наберите текст диктанта в поле ниже. Если текст стихотворный, каждую строку записывайте отдельно, с большой буквы. В конце нажмите кнопку "ПРОВЕРИТЬ". Вы увидите текст Вашего диктанта с выделенными красным ошибками и оценку. Наведите курсор на слово с ошибкой, рядом Вы увидите орфографическое или пунктуационное правило.

**Comment by GrimGrinPilgrim** [comment]
что опять не так?

**Comment by dendik** [comment]
В репозитории его нет. Или я куда-то не туда смотрю?

**Comment by dendik** [comment]
Вывесил.

**Comment by dendik** [comment]
Одна маленькая беда с ним: восклицательный знак в слишком высоком слое висит. При вопросе "вы уверены, что хотите отправлять текст?" он один светится.

**Comment by GrimGrinPilgrim** [comment]
поправила
