### ISSUE TITLE
Вывесить на страницу со счётчиком контакты для обратной связи.

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#63]
>  Мы сделали ящик zhivoeslovo@totaldict.ru
>    Нужно, наверное, написать текст на странице со счетчиком -
>    ждем ваших замечаний и предложений по совместному проекту Тотального диктанта и программы "Живое слово"
>    zhivoeslovo@totaldict.ru

**Comment by GrimGrinPilgrim** [comment]
запушила в репу, файл anons

**Comment by dendik** [comment]
Вывесил я его только сейчас, чтобы не делать это в спешке и не накосячить.
Вроде всё ок.
