### ISSUE TITLE
Провести инструктаж Антона про дежурство

### ISSUE THREAD

**Issue by dendik** [Alenush/zhivoeslovo#71]
- завести аккаунт
- разложить данные так, чтобы у Антона был доступ
- протестировать несколько нештатных ситуаций
- пройти и дополнить протокол обновления сервера
- протестировать перезагрузку

**Comment by dendik** [comment]
Инструктаж провели, впрочем, тренировки нештатных ситуаций не было.

**Comment by avybornova** [comment]
А запись осталась?:)

**Comment by dendik** [comment]
См. #76
